steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/agencia-bekor/webapp-planner','.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/agencia-bekor/webapp-planner']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'webapp-planner', '--image', 'gcr.io/agencia-bekor/webapp-planner', '--region', 'us-central1', '--platform', 'managed']
images:
- gcr.io/agencia-bekor/webapp-planner