steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/agencia-bekor/webapp-planner','.']
# Running container
- name: 'docker'
  args: ['run','-d', '--name','webapp-planner','gcr.io/agencia-bekor/webapp-planner']
- name: 'docker'
  args: ['exec','php', 'artisan', 'config:cache']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/agencia-bekor/webapp-planner']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/agencia-bekor/webapp-planner', '--region', 'REGION', '--platform', 'managed']
images:
- gcr.io/agencia-bekor/webapp-planner